function sim = pal_tapas_est2sim(est, the_seed)

% as the name suggests
% turn est output from tapas_fitModel into a simulation

% Input validation and return of []: TBD
if isempty(est)
    disp('warning: empty input') %somehow warning cannot be printed??
    sim = [];
    return
end
if ~exist('the_seed','var')
    sim = tapas_simModel(est.u,...
        func2str(est.c_prc.prc_fun),...
        est.p_prc.p,...
        func2str(est.c_obs.obs_fun),...
        est.p_obs.p);
else
    sim = tapas_simModel(est.u,...
        func2str(est.c_prc.prc_fun),...
        est.p_prc.p,...
        func2str(est.c_obs.obs_fun),...
        est.p_obs.p,...
        the_seed);
end

end